/* Emit the heuristic's tables as RV32I assembler data for Ripes.
 *
 * The heuristic lives in its own C file, included below through
 * HEURISTIC_SOURCE (a path relative to this file), exactly as for
 * check_heuristic. After heuristic_init() runs, its four tables are printed
 * in their C layout (row-major, element sizes unchanged):
 *
 *   perm_next    .half  [3][5040]   perm_next + 2 * (face * 5040 + p)
 *   orient_next  .half  [3][729]    orient_next + 2 * (face * 729 + o)
 *   dist_p       .byte  [5040]      dist_p + p
 *   dist_o       .byte  [729]       dist_o + o
 *
 * The output opens with .align 2, so the .half tables start on an even
 * address even when the program's own .data (such as the 15-byte input
 * string) comes first. Ripes reads the .align operand as a byte count, not
 * a power of two: .align 2 pads to a multiple of 2.
 * The .half tables precede the .byte ones so they stay aligned too.
 *
 * Build and run from the repository root:
 *   cc -O2 -std=c99 -DHEURISTIC_SOURCE='"../heuristic.c"' \
 *      tools/gen_tables.c -o gen_tables
 *   ./gen_tables > tables.s
 *
 * Ripes takes a single source file, so append the output to the program:
 *   cat solve.s tables.s > build.s
 *
 * Exit status is nonzero if a distance table has an unset entry.
 */
#include "oracle.h"

#ifndef HEURISTIC_SOURCE
#error "define HEURISTIC_SOURCE, e.g. -DHEURISTIC_SOURCE='\"../heuristic.c\"'"
#endif
#include HEURISTIC_SOURCE

enum { PER_LINE = 16 };

static void emit_table(const char *label, const char *directive,
                       const void *table, uint32_t count, uint32_t width)
{
    printf("\n%s:\n", label);
    for (uint32_t i = 0; i < count; i += PER_LINE) {
        printf("    %s ", directive);
        for (uint32_t j = i; j < count && j < i + PER_LINE; ++j) {
            uint32_t value = width == 2 ? ((const uint16_t *) table)[j]
                                        : ((const uint8_t *) table)[j];
            printf("%s%u", j == i ? "" : ", ", value);
        }
        putchar('\n');
    }
}

static int unset_entries(const uint8_t *table, uint32_t size)
{
    for (uint32_t i = 0; i < size; ++i)
        if (table[i] == UNSET)
            return 1;
    return 0;
}

int main(void)
{
    heuristic_init();
    if (unset_entries(dist_p, PERMUTATIONS) ||
        unset_entries(dist_o, ORIENTATIONS)) {
        fputs("a distance table has an unset entry\n", stderr);
        return 1;
    }

    uint32_t bytes = (uint32_t) (sizeof perm_next + sizeof orient_next +
                                 sizeof dist_p + sizeof dist_o);
    printf("\n# Generated by tools/gen_tables.c; do not edit.\n");
    printf("# %u bytes of static data.\n", bytes);
    printf(".data\n.align 2\n");
    emit_table("perm_next", ".half", perm_next, 3 * PERMUTATIONS, 2);
    emit_table("orient_next", ".half", orient_next, 3 * ORIENTATIONS, 2);
    emit_table("dist_p", ".byte", dist_p, PERMUTATIONS, 1);
    emit_table("dist_o", ".byte", dist_o, ORIENTATIONS, 1);
    return ferror(stdout) || fflush(stdout) != 0;
}
